#!/bin/bash

#################################################
# Zimbra restore script for open source edition #
#################################################

ZIMBRA_HOME=/opt/zimbra
ZIMBRA_BIN=$ZIMBRA_HOME/bin
ZIMBRA_RESTORE_DIR=$ZIMBRA_HOME/backup 

RESTORE_DATE=`date +%G-%m-%d_%H-%M` 

# set default option is 0 (unset)
VERBOSE=0 

source $ZIMBRA_BIN/zmshutil || exit 1
zmsetvars \
	zimbra_server_hostname 

log()
{
    # verbose option is turn on
    if [ $VERBOSE -eq 1 ]; then
        echo $1
    fi
}

usage() 
{

    cat << EOF
zmrestore: zmrestore [-o path] -a|-u mailbox [-f file]
EOF

}

restore_mailbox()
{
    mbox=$1
    log "start restore mailbox $mbox"
    zimbraMailSSLPort=`zmprov gs $zimbra_server_hostname zimbraMailSSLPort | egrep -v -e '^(#|$)' | cut -d ' ' -f 2`
    if [ -z "$zimbraMailSSLPort" ] ; then
      log "ERROR: Cannot find zimbraMailSSLPort"
      exit 1
    fi
    if [ ! -z "$2" -a -z "$3" ] ; then
        if [ -f $ZIMBRA_RESTORE_DIR/$2/$mbox-$RESTORE_DATE.tgz ] ; then
          log "$ZIMBRA_BIN/zmmailbox -v -z -m $mbox postRestURL -u https://${zimbra_server_hostname}:${zimbraMailSSLPort} '//?fmt=tgz&resolve=reset' $ZIMBRA_RESTORE_DIR/$2/$mbox-$RESTORE_DATE.tgz"
          $ZIMBRA_BIN/zmmailbox -v -z -m $mbox postRestURL -u https://${zimbra_server_hostname}:${zimbraMailSSLPort} '//?fmt=tgz&resolve=reset' $ZIMBRA_RESTORE_DIR/$2/$mbox-$RESTORE_DATE.tgz
          log "restore mailbox $mbox from $ZIMBRA_RESTORE_DIR/$2/$mbox-$RESTORE_DATE.tgz successful"
        else
          log "ERROR: Cannot restore mailbox $mbox from $ZIMBRA_RESTORE_DIR/$2/$mbox-$RESTORE_DATE.tgz - File Not Found"
          exit 5
        fi
    else
      if [ ! -z "$3" ]; then
        $ZIMBRA_BIN/zmmailbox -v -z -m $mbox postRestURL -u https://${zimbra_server_hostname}:${zimbraMailSSLPort} "//?fmt=tgz&resolve=reset" $3 
        log "restore mailbox $mbox from $3 successful"
      else
        $ZIMBRA_BIN/zmmailbox -v -z -m $mbox postRestURL -u https://${zimbra_server_hostname}:${zimbraMailSSLPort} "//?fmt=tgz&resolve=reset" $ZIMBRA_RESTORE_DIR/$mbox-$RESTORE_DATE.tgz 
        log "restore mailbox $mbox from $ZIMBRA_RESTORE_DIR successful"
      fi
    fi
} 

create_pack_restore()
{   
    log "search domain"
    domains=`$ZIMBRA_BIN/zmprov gad`

    for domain in $domains; do
        log "start restore domain $domain" 

        # get all accounts from domain
        mboxs=`$ZIMBRA_BIN/zmprov -l gaa $domain`

        # check directory if -o is set
        mkdir -p $ZIMBRA_RESTORE_DIR/$domain

        # fetch account in tgz format
        for mbox in $mboxs; do
#            $ZIMBRA_BIN/zmmailbox -z -m $mbox getRestURL "//?fmt=tgz&resolve=reset" > $ZIMBRA_RESTORE_DIR/$domain/$mbox-$RESTORE_DATE.tgz
            restore_mailbox $mbox $domain
        done

        # pack mailbox in domain
        cd $ZIMBRA_RESTORE_DIR/$domain
        tar czf $domain-$RESTORE_DATE.tgz `ls`
        mv $domain-$RESTORE_DATE.tgz $ZIMBRA_RESTORE_DIR
        cd $ZIMBRA_RESTORE_DIR
        rm -rf $ZIMBRA_RESTORE_DIR/$domain
        
        log "restore domain $domain successful"

    done
}

# Option
# zmrestore [-ah] [-u mailbox] [-o path] [-f backupfile]
while getopts :aho:u:f:v OPTION; do
    case $OPTION in
        a )
            AFLAG=1
            ;;
        h )
            usage
            ;;
        o )
            if [ -z $OPTARG ]; then
                echo "-o option must specific path"
                exit 1
            else
                ZIMBRA_RESTORE_DIR=${OPTARG:0:${#OPTARG}-1} # substring from 0 to strlen - 1
            fi
            ;;
        u ) 
            if [ -z $OPTARG ]; then
                echo "-u option must specific mailbox"
            else
                UFLAG=$OPTARG
            fi
            ;;
        f ) 
            if [ -z $OPTARG ]; then
                echo "-f option must specify an existing backup file"
            else
                UFILE=$OPTARG
            fi
            ;;
        v )
            VERBOSE=1
            ;;
        # other option doesn't match
        * )
            usage
            exit 1
            ;;
    esac
done

# if not specific -a or -u it error and exit the script
if [ -z $UFLAG ] && [[ $AFLAG -ne 1 ]]; then
    echo "you must specific -a or -u option"
    exit 1
fi

# if UFLAG has value but AFLAG is used
if [ ! -z $UFLAG ] && [[ $AFLAG -eq 1 ]]; then
    echo "use -a or -u"
    exit 1
# if declare UFLAG
elif [ ! -z $UFLAG ]; then
    restore_mailbox $UFLAG from-file $UFILE
fi

# if AFLAG on
if [[ $AFLAG -eq 1 ]]; then
    create_pack_retore
fi
